/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClaimContract } from "./ClaimContract";
export * as factories from "./factories";
export { ClaimContract__factory } from "./factories/ClaimContract__factory";
